esphome:
  name: open-air-mini
  friendly_name: "Open Air Mini"

esp32: 
  variant: esp32

# Enable logging
logger:
  level: DEBUG

# This is optional and can be commented out to disable the Web Server
web_server:
  port: 80

# Enable Home Assistant API
api:
  port: 6053

# ota:
#   - platform: esphome
#   password: "9f2ab9aa715f573e2476e75a5ec7f4e7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Open-AIR-Mini Fallback"
    password: "ChangeMe@123!"

captive_portal:

globals:
  # Max fan speed, when in disconnected mode (linked to disconnected_hum_level_max_speed).
  - id: disconnected_max_fan_speed
    type: int
    restore_value: no
    initial_value: "90"
  # Medium fan speed, when in disconnected mode (linked to disconnected_hum_level_medium_speed).
  - id: disconnected_medium_fan_speed
    type: int
    restore_value: no
    initial_value: "45"
  # Default (fallback) fan speed, for:
    # if humidity is lower than disconnected_hum_level_medium_speed, or
    # if not connected to a humidity sensor
  - id: disconnected_default_fan_speed
    type: int
    restore_value: no
    initial_value: "25"
  # Humidity threshold for enabling max fan speed, when in disconnected mode.
  - id: disconnected_hum_level_max_speed
    type: int
    restore_value: no
    initial_value: "75"
  # Humidity threshold for enabling medium fan speed, when in disconnected mode.
  - id: disconnected_hum_level_medium_speed
    type: int
    restore_value: no
    initial_value: "55"

# From V1.4.0 The Sensor pins on the Open AIR Mini are swapped. Correct example is below:
uart:
#UART For Sensor 2
 - rx_pin: GPIO13
   tx_pin: GPIO12
   baud_rate: 9600
   id: uart_sensor_2
#UART For Sensor 1
 - rx_pin: GPIO25
   tx_pin: GPIO26
   baud_rate: 9600
   id: uart_sensor_1

i2c:
#I2C For Sensor 2
- id: i2c_sensor_2
  sda: GPIO19
  scl: GPIO18
  scan: false
  frequency: 400kHz
#I2C For Sensor 1
- id: i2c_sensor_1
  sda: GPIO16
  scl: GPIO4
  scan: false
  frequency: 400kHz




# Status led
status_led:
  pin:
    number: GPIO33

#PWM output for controlling the motor.
output:
  - platform: ledc
    pin: GPIO15
    inverted: true
    id: open_air_mini

fan:
  - platform: speed
    output: open_air_mini
    name: "Open AIR Mini"
    id: fan_motor

sensor:
  - platform: pulse_counter
    pin: GPIO14
    unit_of_measurement: 'RPM'
    name: 'AIR Mini RPM'
    id: open_air_mini_rpm

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: scd4x
    i2c_id: i2c_sensor_1
    co2:
      name: "Open AIR Mini Sensor Mini x CO2"
      id: air_Co2
      accuracy_decimals: 0
    temperature:
      name: "Open AIR Mini Sensor Mini x Temperature"
      id: air_temperature
      accuracy_decimals: 2
    humidity:
      name: "Open AIR Mini Sensor Mini x Humidity"
      id: air_humidity
      accuracy_decimals: 2
    update_interval: 30s
    measurement_mode: periodic

  - platform: sgp4x
    i2c_id: i2c_sensor_1 
    voc:
      name: "Open AIR Mini x VOC Index "
      id: air_VOC
    nox:
      name: "Open AIR Mini x NOx Index "
      id: air_NOx
    compensation:
      temperature_source: air_temperature #Make sure to match these if you change ID's.
      humidity_source: air_humidity       #Make sure to match these if you change ID's.
    update_interval: 30s

script:
  - id: disconnected_mode
    mode: single
    then:
      - logger.log: "Disconnected Mode Triggered"
      - fan.turn_on:
          id: fan_motor
          speed: !lambda |-
            auto hum = id(air_humidity).state;
            if (hum >= id(disconnected_hum_level_max_speed)) {
              return id(disconnected_max_fan_speed);
            } else if (hum >= id(disconnected_hum_level_medium_speed)) {
              return id(disconnected_medium_fan_speed);
            } else {
              return id(disconnected_default_fan_speed);
            }
            return id(disconnected_default_fan_speed);

interval:
  - interval: 30s
    then:
      - logger.log: "API Connectivity Check for Disconnected Mode"
      - if:
          condition:
            not:
              api.connected:
          then:
            - logger.log: "API disconnected"
            - script.execute: disconnected_mode
          else:
            - logger.log: "API connected"
            - script.stop: disconnected_mode
